services:
  order-postgres:
    image: postgres:17
    container_name: order-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: ${ORDER_DATABASE_USERNAME:-order_user}
      POSTGRES_PASSWORD: ${ORDER_DATABASE_PASSWORD:?Preencha ORDER_DATABASE_PASSWORD no .env}

    ports:
      - "5433:5432"

    volumes:
      - order_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-postgres:
    image: postgres:17
    container_name: inventory-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: ${INVENTORY_DATABASE_USERNAME:-inventory_user}
      POSTGRES_PASSWORD: ${INVENTORY_DATABASE_PASSWORD:?Preencha INVENTORY_DATABASE_PASSWORD no .env}

    ports:
      - "5434:5432"

    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 10s
      timeout: 5s
      retries: 5

  order-rabbitmq:
    image: rabbitmq:4-management
    container_name: order-rabbitmq
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:?Preencha RABBITMQ_PASSWORD no .env}

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - order_rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  order_postgres_data:
  inventory_postgres_data:
  order_rabbitmq_data:
