spring.application.name=order-service
# PostgreSQL
spring.datasource.url=${ORDER_DATABASE_URL:jdbc:postgresql://localhost:5433/order_db}
spring.datasource.username=${ORDER_DATABASE_USERNAME:order_user}
spring.datasource.password=${ORDER_DATABASE_PASSWORD:order_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Servidor
server.port=8081

# Actuator
management.endpoints.web.exposure.include=health,info